/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "otazlcgepsrxlcljnpwu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90YXpsY2dlcHNyeGxjbGpucHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTExNzQsImV4cCI6MjA3MzY2NzE3NH0.Gmp-LonvEgih3hl8b0-r3U00S708oDLwwgQBxqMREl4"